export const SERVICE_BASKET_COUNT           = 'SERVICE_BASKET_COUNT';

export const FETCH_CATEGORIES_REQUEST       = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_ERROR         = 'FETCH_CATEGORIES_ERROR';
export const FETCH_CATEGORIES_SUCCESS       = 'FETCH_CATEGORIES_SUCCESS';

export const FETCH_CATEGORIES_ITEMS_REQUEST = 'FETCH_CATEGORIES_ITEMS_REQUEST';
export const FETCH_CATEGORIES_ITEMS_ERROR   = 'FETCH_CATEGORIES_ITEMS_ERROR';
export const FETCH_CATEGORIES_ITEMS_SUCCESS = 'FETCH_CATEGORIES_ITEMS_SUCCESS';

export const SEARCH_ITEM                    = 'SEARCH_ITEM';

export const FETCH_TOP_ITEMS_REQUEST        = 'FETCH_TOP_ITEMS_REQUEST';
export const FETCH_TOP_ITEMS_FAILURE        = 'FETCH_TOP_ITEMS_FAILURE';
export const FETCH_TOP_ITEMS_SUCCESS        = 'FETCH_TOP_ITEMS_SUCCESS';



